In [20]:
import numpy as np
x = np.arange(10)
i = np.array([2, 2,2, 8, 4])
x[i] = 99

print x

[ 0  1 99  3 99  5  6  7 99  9]


In [21]:
x[i] -= 10
x

array([ 0,  1, 89,  3, 89,  5,  6,  7, 89,  9])

In [19]:
y = np.zeros(10)
y[[0, 0]] = [4, 6]
i = np.array([2, 3, 3, 4, 4, 4])
y[i] += 1
y

array([ 6.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.])

https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html